# SPDX-FileCopyrightText: 2026 Kipila Ltd
# SPDX-License-Identifier: Apache-2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: name-tests-test
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
        args: [--check]
  - repo: local
    hooks:
      - id: basedpyright
        stages: [pre-commit]
        name: basedpyright
        entry: uv run basedpyright
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
